services:
      
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "payment_db"
      POSTGRES_USER: "payment_user"
      POSTGRES_PASSWORD: "payment_pass"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - monero-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: "jkdev@test.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "8081:80"
    depends_on:
      - postgres
    networks:
      - monero-network
    volumes:
      - pgadmin_data:/var/lib/pgadmin

networks:
  monero-network:
    name: monero-network
volumes:
  postgres_data:
  pgadmin_data: